### ISSUE TITLE
Destacar botão usado para mover slider na barra do tempo

### ISSUE THREAD

**Issue by hguerra** [hguerra/publish-next#12]
Destacar botão usado para mover slider na barra do tempo, adicionar sombra ou cor que diferencie:

![image](https://user-images.githubusercontent.com/7364383/104846702-a3c9ba00-58ba-11eb-9236-0e954766cc99.png)

**Comment by faahbih** [comment]
![4](https://user-images.githubusercontent.com/11638717/110702740-af0dd780-81d1-11eb-8698-7de57e88c56b.png)
![3](https://user-images.githubusercontent.com/11638717/110702743-b03f0480-81d1-11eb-8dba-31ca94e12bff.png)

**Comment by hguerra** [comment]
@faahbih, relacionado com #27.

![image](https://user-images.githubusercontent.com/7364383/110714659-9b1ea180-81e2-11eb-9544-46e1308cfe11.png)
