### ISSUE TITLE
Criar protótipo no Figma de botão para mostrar uma gráfico com todos os biomas

### ISSUE THREAD

**Issue by hguerra** [hguerra/publish-next#23]
Pensar em uma maneira na interface de mostrar um gráfico com todos os biomas ao mesmo tempo

**Comment by faahbih** [comment]
![1 (1)](https://user-images.githubusercontent.com/11638717/110662719-88857780-81a4-11eb-95cf-94e56ab32e74.png)
![2 (1)](https://user-images.githubusercontent.com/11638717/110662715-87544a80-81a4-11eb-80e4-81dc309a3344.png)

**Comment by faahbih** [comment]
@hguerra o gráfico vai ficar separado ou vai ser um só pra todos os biomas?

**Comment by hguerra** [comment]
@faahbih, alinhando com o Pedro será um gráfico para todos os biomas. As linha desenhas serão das mesmas cores da legenda.

**Comment by hguerra** [comment]
![image](https://user-images.githubusercontent.com/7364383/110714146-d66ca080-81e1-11eb-82e7-7061e409a38c.png)

**Comment by faahbih** [comment]
@hguerra isso? Dúvida: vai abrir o modal de cada bioma ao invés de clicar no mapa, ou no mapa vai continuar tendo o evento de abrir o modal e vai ter essa outra opção de clique em cada bioma pela legenda tbm? 

![4](https://user-images.githubusercontent.com/11638717/110786283-b45b3880-824a-11eb-97f7-952b258542fd.png)
![5](https://user-images.githubusercontent.com/11638717/110786275-b32a0b80-824a-11eb-90a8-c68efc3d0d1e.png)

**Comment by hguerra** [comment]
@faahbih, vamos manter os dois eventos, abrir a modal pelo mapa ou pela legenda. Na imagem acima acho que o ideal é trocar o checkbox por um botão.

**Comment by faahbih** [comment]
**Alternativa 1**

![4](https://user-images.githubusercontent.com/11638717/110941488-34e76b00-8317-11eb-91c1-4a8eeaaef489.png)
![5](https://user-images.githubusercontent.com/11638717/110941485-33b63e00-8317-11eb-9ee9-567b5bc787a0.png)

**Alternativa 2**
![4 (1)](https://user-images.githubusercontent.com/11638717/110941675-809a1480-8317-11eb-847e-df95d992cfa2.png)

**Comment by faahbih** [comment]
[>>> Protótipo atualizado ](https://www.figma.com/proto/0WAvHMt2OSDmabESGMJTPb/Publish-2?node-id=448%3A6163&scaling=min-zoom)

![v2](https://user-images.githubusercontent.com/11638717/111302227-e3e6b800-8631-11eb-89d6-e3c4277d55f7.png)
![v2-1](https://user-images.githubusercontent.com/11638717/111302233-e5b07b80-8631-11eb-99ec-fd6910d86882.png)
![v2-2](https://user-images.githubusercontent.com/11638717/111302240-e812d580-8631-11eb-947d-9feb66875250.png)
![v2-3](https://user-images.githubusercontent.com/11638717/111302247-e9dc9900-8631-11eb-83f4-def8887847df.png)

**Comment by faahbih** [comment]
[prototipo v3](https://www.figma.com/proto/0WAvHMt2OSDmabESGMJTPb/Publish-2?node-id=474%3A7341&scaling=min-zoom)

![legend+btn](https://user-images.githubusercontent.com/11638717/111468384-41e3d000-8704-11eb-81fe-370d75c6d393.png)
