### ISSUE TITLE
Criar protótipo no Figma de cor do texto do tooltip do mapa

### ISSUE THREAD

**Issue by hguerra** [hguerra/publish-next#25]
Na diferença para 2000, pensar se a cor do balão poderia ser usada para indicar valores positivos ou negativos. lembrando que não pode usar vermelho nem verde, pois a depender do atributo selecionado vermelho pode ser o oposto. pensei em algo tipo azul para aumento e cinza ou amarelo para diminuição, mas teria que ver como fica.

**Comment by faahbih** [comment]
[
![UI Publish-Modal](https://user-images.githubusercontent.com/11638717/110530146-de9ce100-80f8-11eb-9cc9-e1f631832a61.png)

![UI Publish-Modal-1](https://user-images.githubusercontent.com/11638717/110530157-e197d180-80f8-11eb-9609-3f7b49318d82.png)

]

**Comment by hguerra** [comment]
@faahbih, Pedro solicitou as seguintes alterações:

![image](https://user-images.githubusercontent.com/7364383/110714453-29deee80-81e2-11eb-9b4e-eb9b83d1a4ad.png)

**Comment by faahbih** [comment]
@hguerra assim?

![1](https://user-images.githubusercontent.com/11638717/110783260-f3878a80-8246-11eb-936b-8ffa5358c061.png)

**Comment by faahbih** [comment]
https://www.chartjs.org/docs/latest/configuration/tooltip.html?h=tooltip
