### ISSUE TITLE
Criar protótipo Figma com a cor do botão da linha do tempo igual a do cenário

### ISSUE THREAD

**Issue by hguerra** [hguerra/publish-next#27]
Criar protótipo para validar o layout caso o botão da linha do tempo seja da mesma cor do cenário selecionado:

![image](https://user-images.githubusercontent.com/7364383/109559133-0ff22d00-7ab9-11eb-83a4-d6f36f90a6e1.png)

**Comment by faahbih** [comment]
![2 (1)](https://user-images.githubusercontent.com/11638717/110631860-bdce9d00-8185-11eb-98e7-41d829426ef0.png)
![1 (1)](https://user-images.githubusercontent.com/11638717/110631864-beffca00-8185-11eb-9db2-8c0c297647a0.png)

**Comment by hguerra** [comment]
@faahbih, vamos seguir com:
![image](https://user-images.githubusercontent.com/7364383/110714692-a83b9080-81e2-11eb-95bb-d1163b7019a9.png)
